/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** 归一化文本：可选去除空白 / 转小写 */
export interface NormalizeOptions {
  trim?: boolean
  lowercase?: boolean
}
export declare function normalize(input: string, options?: NormalizeOptions | undefined | null): string
/**
 * 统计 token 数量（简化实现：按空白分词 + 标点计数）
 * 生产环境可替换为 tiktoken-rs 等真实 tokenizer
 */
export declare function countTokens(input: string): number
/** 计算 SHA-256 十六进制摘要 */
export declare function sha256Hex(input: string): string
